### ISSUE TITLE
[enhancement] Add missing bower.json.

### ISSUE THREAD

**Issue by timgluz** [jeromeetienne/threex.geometricglow#2]
#### Hey, maintainer(s) of jeromeetienne/threex.geometricglow!

We at [VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) are working hard to keep up the quality of the bower's registry.

We just finished our initial analysis of the quality of the Bower.io registry:

**7530** - registered packages, _224_ of them doesnt exists anymore;

We analysed **7306**  existing packages and  **1070** of them don't have bower.json on the master branch ( _that's where a Bower client pulls a data_ ).

Sadly, your library `jeromeetienne/threex.geometricglow` is one of them.

Can you spare **15** minutes to help us to make Bower better?

Just add a new file `bower.json` and  change attributes.

```
{
  "name": "jeromeetienne/threex.geometricglow",
  "version": "1.0.0",
  "main": "path/to/main.css",
  "description": "please add it",
  "license": "Eclipse",
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
    "<dependency_name>": "<semantic_version>",
    "<dependency_name>": "<Local_folder>",
    "<dependency_name>": "<package>"
  },
  "devDependencies": {
    "<test-framework-name>": "<version>"
  }
}

```

Read more about bower.json [on the official spefication](http://bower.io/#defining-a-package) and nodejs [semver](https://github.com/isaacs/node-semver#ranges) library has great examples of proper versioning.

**NB!** Please _validate_ your bower.json with _jsonlint_ before commiting your updates.

Thank you!

Timo,
twitter: @versioneye
email: timo@versioneye.com
[VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) - no more legacy software!

**Comment by jeromeetienne** [comment]
@timgluz spamming people who participate to opensource is shameful. they work for free for other. you should respect that and spam elsewhere

**Comment by timgluz** [comment]
well, i agree that; But when you register your packages on Bower.io, you should follow their specifications; i work on opensource libraries too and it's pain to keep eye on licenses and subdependencies;

**Comment by jeromeetienne** [comment]
well you spam and you come here giving me advices on how to handle open
source and how to help users ? i dont think you are serious :)

**Comment by jeromeetienne** [comment]
if you were serious, you would correct your mistake, and close all the
issues your bot opened.

**Comment by timgluz** [comment]
Yes, i'll do that; but can you add missing bower.json files then?

**Comment by jeromeetienne** [comment]
for history, here is the proof of the 65 emails your bots sent me. i hope it helps make you realize how mistaken your approach is. thanks for closing the issues. 

![screen shot 2014-01-07 at 5 09 42 pm](https://f.cloud.github.com/assets/252962/1860643/8129cd10-77b6-11e3-9346-e1f693860174.png)

**Comment by timgluz** [comment]
Ok, point taken;

Fact is that you have many packages registered on Bower.io and none of them has bower.json; 
When you had published your packages properly on Bower, then you wouldnt get any of this emails.
Maybe you should remove all your packages on bower.io and stop polluting that list?

**Comment by jeromeetienne** [comment]
@timgluz as said before, you are a spammer trying to give ethical lessons. It isn't convincing. let bower people handle bower, dont act as if you were responsable for bower. and stop spamming people. We are not at all talking about tech matter. just your attitude of sending mass emails to promote your product.

even if you were technically correct, nothing would justify 65 emails spam in a single day. nobody in opensource world would accept that. ask around.

if you have bug to report, please do so. but dont be confused, to report a bug isnt to have a bot send 65emails. it is a clear short description of a error. not an automatic emails giving 3 times links on your product.

another possibility if you thought you found a bug would have been a pull request. this is the common way to contribute to others code. a more productive one :)

**Comment by jeromeetienne** [comment]
@timgluz i reported you thus we wont waste our mutual time in the future. no hard feeling.
